[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "videotuna-tutorial"
authors = [{name = "VideoTuna Team"}]
dynamic = ["version", "description"]
requires-python = ">=3.8"
